
package com.letsgo.routingclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IItineraryService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IItineraryService {


    /**
     * 
     * @param origin
     * @param destination
     * @return
     *     returns com.letsgo.routingclient.ItineraryDto
     */
    @WebMethod(operationName = "GetItinerary", action = "http://tempuri.org/IItineraryService/GetItinerary")
    @WebResult(name = "GetItineraryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItinerary", targetNamespace = "http://tempuri.org/", className = "com.letsgo.routingclient.GetItinerary")
    @ResponseWrapper(localName = "GetItineraryResponse", targetNamespace = "http://tempuri.org/", className = "com.letsgo.routingclient.GetItineraryResponse")
    public ItineraryDto getItinerary(
        @WebParam(name = "origin", targetNamespace = "http://tempuri.org/")
        String origin,
        @WebParam(name = "destination", targetNamespace = "http://tempuri.org/")
        String destination);

    /**
     * 
     * @param originLat
     * @param destLon
     * @param originLon
     * @param destLat
     * @return
     *     returns com.letsgo.routingclient.ItineraryDto
     */
    @WebMethod(operationName = "GetItineraryByCoords", action = "http://tempuri.org/IItineraryService/GetItineraryByCoords")
    @WebResult(name = "GetItineraryByCoordsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetItineraryByCoords", targetNamespace = "http://tempuri.org/", className = "com.letsgo.routingclient.GetItineraryByCoords")
    @ResponseWrapper(localName = "GetItineraryByCoordsResponse", targetNamespace = "http://tempuri.org/", className = "com.letsgo.routingclient.GetItineraryByCoordsResponse")
    public ItineraryDto getItineraryByCoords(
        @WebParam(name = "originLat", targetNamespace = "http://tempuri.org/")
        String originLat,
        @WebParam(name = "originLon", targetNamespace = "http://tempuri.org/")
        String originLon,
        @WebParam(name = "destLat", targetNamespace = "http://tempuri.org/")
        String destLat,
        @WebParam(name = "destLon", targetNamespace = "http://tempuri.org/")
        String destLon);

}
